### ISSUE TITLE
Latest versioned-functions should always be exposed

### ISSUE THREAD

**Issue by ymtszw** [y047aka/elm-reset-css#3]
Currently `latest` functions such as https://package.elm-lang.org/packages/y047aka/elm-reset-css/latest/Css-Reset-Destyle#latest target to actual implementations in their internal modules.

However, those internal functions aren't exposed until they became non-latest. For instance `Destyle.v3` won't appear until v4 of Destyle is released in the current style.

This release style is problematic when users want to "lock" their reset versions proactively. Like so:

1. A user is happy with Destyle v3
2. They checked Destyle v4-rc.1 and found it has unfavorable changes so they want to keep using v3
3. But to use v3, `Css.Reset.Destyle.latest` must be called from their code for now
4. If a new version of `elm-css-reset` came out, they have to (a) bump the dep, and (b) rewrite `latest` to `v3` explicitly at this moment

If `v3` was exposed when they had originally implemented, the step 4 can be done proactively.

Also, if a user isn't  aware of the forthcoming change, and was using `latest`, their css reset will unexpectedly change when they bump `elm-css-reset`!
(To this end I personally do not recommend using `latest` and always use explicitly versioned ones, but anyway.)

**Comment by y047aka** [comment]
Thanks for reporting this.
I've opened the PR https://github.com/y047aka/elm-reset-css/pull/5 .
