### ISSUE TITLE
Loosen elm-css dependency range

### ISSUE THREAD

**Issue by ymtszw** [y047aka/elm-reset-css#4]
Latest elm-reset-css (2.5.0) depends on `rtfeldman/elm-css 17.0.1 <= v < 18.0.0` but it sure had worked with elm-css 16.

And apparently this package does not depend on particular behavior of elm-css 17+ so the requirements should and can be loosened to `16.0.0 <= v < 18.0.0` for now.

**Comment by y047aka** [comment]
Thank you.
I made it so. https://github.com/y047aka/elm-reset-css/pull/6
